### ISSUE TITLE
Release v1.0.9

### ISSUE THREAD

**Issue by mitchdz** [aws/amazon-ec2-hibinit-agent#45]
I'm an Ubuntu package maintainer and am looking to upgrade the Ubuntu package to get the latest improvements in for Oracular.

It would help if the latest commit could be made into a release since the last release was a while ago.

**Comment by mitchdz** [comment]
Also I am curious if there is any defined release cadence?

**Comment by secarola** [comment]
Hi, 

Unfortunately the [Ubuntu Agent](https://launchpad.net/ubuntu/+source/ec2-hibinit-agent) has been forked from this repository for a while now. There is a good amount of work that'll be required in order to realign the two agents (for one they use different swap file names, and changing that for whichever OS will require new code to handle the potential existence of an unexpected swap file). 

The most recent commit is required for Ubuntu ARM, but has been added here to keep the two repositories from forking further. If you are grabbing this and other improvements made to this agent I would recommend careful testing afterwards. (For example, the testing done on Ubuntu was using the existing Ubuntu agent, with the commit patched in - details [more testing details here](https://bugs.launchpad.net/ubuntu/+source/linux-aws/+bug/2060992/comments/4)). 

I will still create a new release with the latest commits (Release v1.0.9). 

There is no defined release cadence, changes to the agent are limited and there will be a new release with any new feature or bug fix. (It was a miss on this latest commit to not create the new release, thanks for catching it!)

**Comment by mitchdz** [comment]
Hi Seth! Thanks for the fast response, and thanks for creating the release.

> Unfortunately the [Ubuntu Agent](https://launchpad.net/ubuntu/+source/ec2-hibinit-agent) has been forked from this repository for a while now.

That's exactly why I am doing the work to update it :) 

Ideally I'd like the Ubuntu agent and this one to have no deltas, but your example with the change of `/swap` to `/swap-hibinit` is a good example of a delta that would be hard to squash at this point.

As a heads up - I'll see if I can integrate some Ubuntu deltas during my merge this cycle so we don't diverge too much.

**Comment by mitchdz** [comment]
Also re: testing, I hate doing things manually, so I test with a script that does everything for me from the commandline for initial testing and let CI/CD take over the testing after.

You might be interested in the script I've made for my personal use (although I'm sure you might have your own, I just love sharing). You can find it here if you are interested with an example of how I use it in the README https://github.com/mitchdz/mitch-awstool

**Comment by secarola** [comment]
Fix merged in this [pull request](https://github.com/aws/amazon-ec2-hibinit-agent/pull/46). Please let me know the timeline for getting the updates into the released version of the agent (specifically Jammy and Focal and [this commit](https://github.com/aws/amazon-ec2-hibinit-agent/commit/6994c9a1d9c6ceda835c3391f12d05ca98daf5aa) that is required for Ubuntu ARM Hibernation support).

**Comment by secarola** [comment]
Hi, I am closing out this issue as the fix has been merged in the above pull request and the main commit has been merged into [canonicals repo](https://bugs.launchpad.net/ubuntu/+source/ec2-hibinit-agent/+bug/2066999). Feel free to reopen if there any more questions/asks.
